### ISSUE TITLE
unnecessary files are processed in the parallel implementation

### ISSUE THREAD

**Issue by khoury** [bioidiap/bob.bio.base#1]
It seems that the 'groups' argument is overwritten by its defaults value ('dev') while running the parallel implementation.
Changes in bob/bio/base/script/verify.py are needed.

**Comment by khoury** [comment]
It's now fixed with this commit: 6a8e929a5015a86de38c78fb37d9a4ec1b05cb99

**Comment by siebenkopf** [comment]
I don't think that this was necessary. In general, the whole command line is replicated in the call of the parallel process, see https://github.com/bioidiap/bob.bio.base/blob/master/bob/bio/base/tools/grid.py#L61
https://github.com/bioidiap/bob.bio.base/blob/master/bob/bio/base/tools/grid.py#L79

So, overwriting the ``--groups`` with ``args.groups`` is simply telling the parallel process, that it should overwrite the default (``--groups dev``) with the default. I mean, it doesn't hurt, but it is not necessary.

**Comment by khoury** [comment]
Actually, I found it necessary when I developed a toolchain for only training the background model, in which processing the 'dev' set is not needed.

**Comment by siebenkopf** [comment]
I am not sure, why you needed it (maybe you were manipulating the ``args.groups`` by hand), but I don't think that it is a good solution to change the default behavior in the base package, when you actually need that behavior in a derived package. In the derived packages, you **can** use the tools of the base class, if they fit. If the base tools do not fit, please develop your own tools, instead of fiddling around with the base class tools.

In the given case I am a bit concerned about some side-effects that can happen when you modify base class behavior. For example, look what happens, when you use the ``--groups`` option while submitting jobs, i.e., using the ``--grid`` option. Now, in the grid, the ``--groups`` command line option is passed twice to the script -- once by replicating the command line, and once with your new commit. I think, it is fine as long as both options are identical (in which case your modification is not required), but I don't know, what happens, when they differ.

Maybe you can show me, in which package you needed that behavior, and we might discuss better ways to implement it.

**Comment by khoury** [comment]
Thanks, this discussion helped me to better understand how the jobs are submitted via the grid.
I found a workaround solution that doesn't need my changes in this package. I will revert these changes although I'm not convinced they have side effects.
Indeed my idea was to manipulate 'args.groups' within a script, but found that this manipulation has no effect.
